Book details
shashannkd14/SAD_018 pull request #15
Opened 2020-04-25 09:15 UTC by shashannkd14

@LaxmiNarayanaMurthyVemuri @rehana-ms Please review the request and let us know if any changes are to be made.

@Manaswinich Please make changes to the search again button as discussed.

@SaiTejaKondapalli Once this request is approved you can add your changes

2020-04-26 05:33 UTC, LaxmiNarayanaMurthyVemuri requested changes
Write the testcases for the approutes and functions which you have wrote.use the link here: 
https://www.patricksoftwareblog.com/unit-testing-a-flask-application/

2020-04-27 03:47 UTC, LaxmiNarayanaMurthyVemuri approved these changes

2020-04-27 03:57 UTC, merged

2020-04-27 05:12 UTC, rehana-ms commented on project1/application.py
>          if((uname == users.email) and (hashed_pwd == users.pswd)):
I think you wont get same hash value for the password while logging.Are you able to match the passwords?

2020-04-27 05:19 UTC, shashannkd14 commented on project1/application.py
>          if((uname == users.email) and (hashed_pwd == users.pswd)):
We were able to login with the same user many times, did not face any issue.